version: '2'
services:
  shopfront:
    image: ikbelaloui/iashopfront
    ports:
     - "8010:8010"
    links:
      - productcatalogue
      - stockmanager
  productcatalogue:
    image: ikbelaloui/iaproductcatalogue
    ports:
     - "8020:8020"
  stockmanager:
    image: ikbelaloui/iastockmanager
    ports:
     - "8030:8030"
