---
apiVersion: v1
kind: Service
metadata:
  name: shopfront
  namespace: ikbel
  labels:
    app: shopfront
spec:
  type: NodePort
  selector:
    app: shopfront
  ports:
  - protocol: TCP
    port: 8010
    name: http
  - protocol: TCP
    port: 9100
    name: nodeexporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopfront
  namespace: ikbel
spec:
  selector:
    matchLabels:
      app: shopfront
  replicas: 1
  template:
    metadata:
      labels:
        app: shopfront
    spec:
      containers:
      - name: shopfront
        image: ikbelaloui/iashopfront:latest
        ports:
        - name: http
          containerPort: 8010
        - name: nodeexporter
          containerPort: 9100
        livenessProbe:
          httpGet:
            path: /health
            port: 8010
          initialDelaySeconds: 30
          timeoutSeconds: 1
      imagePullSecrets:
        - name: regcredikbel
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
