---
apiVersion: v1
kind: Service
metadata:
  name: stockmanager
  namespace: ikbel
  labels:
    app: stockmanager
spec:
  type: NodePort
  selector:
    app: stockmanager
  ports:
  - protocol: TCP
    port: 8030
    name: http
  - protocol: TCP
    port: 9100
    name: nodeexporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockmanager
  namespace: ikbel
spec:
  selector:
    matchLabels:
      app: stockmanager
  replicas: 1
  template:
    metadata:
      labels:
        app: stockmanager
    spec:
      containers:
      - name: stockmanager
        image: ikbelaloui/iastockmanager:latest
        ports:
        - name: http
          containerPort: 8030
        - name: nodeexporter
          containerPort: 9100
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8030
          initialDelaySeconds: 30
          timeoutSeconds: 1
      imagePullSecrets:
        - name: regcredikbel
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
